# Generated by Django 3.1.2 on 2020-10-12 20:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiddlePriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('start_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('start_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('end_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('end_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MiddlePriceRange',
                'verbose_name_plural': 'MiddlePriceRanges',
            },
        ),
        migrations.CreateModel(
            name='PriceFilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('under_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('under_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('middle_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('middle_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('above_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('above_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PriceFilterCategory',
                'verbose_name_plural': 'PriceFilterCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('stoke', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('original_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('original_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('current_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('current_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('product_detail', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(related_name='FilterProperty', related_query_name='FilterProperties', to='products.FilterProperties')),
            ],
            options={
                'verbose_name': 'FilterCategory',
                'verbose_name_plural': 'FilterCategories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ManyToManyField(related_name='brand', related_query_name='brand', to='products.Brand')),
                ('filter_category', models.ManyToManyField(related_name='filter_category', related_query_name='filter_categories', to='products.FilterCategory')),
                ('price_filter_category', models.ManyToManyField(related_name='price_filter_category', related_query_name='price_filter_categories', to='products.PriceFilterCategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
