# Generated by Django 3.1.2 on 2020-10-09 21:20

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('original_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('RS', 'RS '), ('USD', 'USD $')], default='IN', editable=False, max_length=3)),
                ('original_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IN', max_digits=14)),
                ('current_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('RS', 'RS '), ('USD', 'USD $')], default='IN', editable=False, max_length=3)),
                ('current_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IN', max_digits=14)),
            ],
        ),
    ]
