version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 99
    reviewers:
      - tejpratap545
      - abhi14nexu
      - ankitpal3722
      - ankyy307000
    assignees:
      - tejpratap545
      - abhi14nexu
    labels:
      - dependencies
    commit-message:
      prefix: node lint fix
      prefix-development: node lint fix
      include: scope

  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 99
    reviewers:
      - tejpratap545
      - abhi14nexu
      - ankitpal3722
      - ankyy307000
    assignees:
      - tejpratap545
      - abhi14nexu
    labels:
      - dependencies
    commit-message:
      prefix: nuxt fix
      prefix-development:  nuxt dev fix
      include: scope


  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 99
    reviewers:
      - tejpratap545
      - abhi14nexu
      - ankitpal3722
      - ankyy307000
    assignees:
      - tejpratap545
      - abhi14nexu
    labels:
      - dependencies
    commit-message:
      prefix: docs fix
      prefix-development: docs fix
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - tejpratap545
      - abhi14nexu
    assignees:
      - tejpratap545
    labels:
      - dependencies
    commit-message:
      prefix: python fix
      prefix-development: python dev fix
      include: scope
