# Generated by Django 3.1.2 on 2020-10-05 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_access_and_refresh_token_model_with_fake_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='access_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_token_apis', to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ),
    ]
