# Generated by Django 3.1.2 on 2020-10-13 22:11

import backend.utils.fileds
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_billingaddress_customer_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='card_expiry',
            field=backend.utils.fileds.CardExpiryField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar'),
        ),
    ]
