# Generated by Django 3.1.2 on 2020-10-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chnage_user_avatar_to_blank_and_null_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profile',
        ),
    ]
