# Generated by Django 3.1.2 on 2020-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201016_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
