# Generated by Django 3.1.2 on 2020-10-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_md5_hash_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('url_token', models.CharField(default='5stBA6B5ZzjjsOKBAUZ9AG9Ui5lzPkY5l4M5Tm9ZHyA', max_length=20)),
                ('success_token', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('token', models.CharField(default='yMjsKe-9SoYYNOev6zGL_kpp9ll2g-GfZNCD25x0hC8', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
