# Generated by Django 3.1.2 on 2020-10-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201021_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='dXo1bRbve-D-1pFGtevklaDvarchdZyfMSObibWj0Xg', max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='zNJ2_n5viJcqnKqh-HP-IBOg7rA_n-FEMrXEk3mnRu4', max_length=250),
        ),
    ]
