# Generated by Django 3.1.2 on 2020-10-21 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201021_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='u0-0Pm80IRgk5OLJj2HTChIcemJMWdhKY8Kv1tv76dE', max_length=250),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='zFWVX3XmTRupCasd0T9zX6G4pArN-cLsf0bRy8YIAvA', max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
