# Generated by Django 3.1.2 on 2020-10-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_update_uuid_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmation',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='VGHg0itlTBFAUIYBb-pKqD6BE0Ca0GTSC9-DbG7I42o', max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='dQii524JSuITe3N9dHR8NpwxbHLg5GgqD24Mmc5oSwA', max_length=250),
        ),
    ]
