# Generated by Django 3.1.2 on 2020-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201021_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='7wVAB75lTJ45i7R3cdlzKU8i53onG11cbh54tzTS4Cc', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='success_token',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='op8I0tPbeWxb6RrUSc3OhbxmV7Ppg3Fopq2NgiHp3U8', editable=False, max_length=250),
        ),
    ]
