# Generated by Django 3.1.2 on 2020-10-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201024_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='jxCoXy69_SGAbcb5xoZI5UAe7IJmRkVpPw63pZ6R6cU', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='kCAArWlIoZIwFzFgd5qKywy_jGPk665XxUnFlwVFdSY', editable=False, max_length=250),
        ),
    ]
