# Generated by Django 3.1.2 on 2020-10-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201024_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='W6fno_0FejiMeDqZj8F2JBhI-7YgF4iqP-d2PoQ6v4w', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='wIWrLYDPbw47dWYGBGfk_UoAStoXP-h0UqcvlQnRnPQ', editable=False, max_length=250),
        ),
    ]
