# Generated by Django 3.1.2 on 2020-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201024_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='xKPyKKNhC1arNfLYrbg4gjFrtXkKo7vAvY3BxWB0F7I', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='JwMJB8srmyd7IUNhfwbeckvfzMjzB90PBc-nfKP_xn4', editable=False, max_length=250),
        ),
    ]
