# Generated by Django 3.1.2 on 2020-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201024_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='d0seW79HG1spfQPnOBDGeIUpOJqeKP89nPEnsGcrWww', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='6IxMm2_ThzW3Ff6yOtMNz5nIg-RTLuSRw2VHL9gWL0w', editable=False, max_length=250),
        ),
    ]
