# Generated by Django 3.1.2 on 2020-10-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201024_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='RA7heBeZqDQv6a3MFguvylO7TJz1tt2bCy-XKBUwEoI', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='JpbjW7oETh14_zHMizrYTz87lPaptDJEbwkaO6q-6DI', editable=False, max_length=250),
        ),
    ]
