# Generated by Django 3.1.2 on 2020-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201024_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='dmBjjO91UfDjtuKsitaFdyRtbzkN9j51489tdhsKkf4', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='SxhKRIAfd6fqOfT7xIZuZH3h5FfIx9Ryv_XQOCMrgyA', editable=False, max_length=250),
        ),
    ]
