# Generated by Django 3.1.2 on 2020-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_create_brand_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='MIuYoORGMUPVJ5ncxGSIgRQX30OZlAOFA3uIwC1e204', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='qWXugDWyVCVOe1vkU0qYyDwvpw1eTZ95MZhxrivjFZA', editable=False, max_length=250),
        ),
    ]
