# Generated by Django 3.1.2 on 2020-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_create_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='R92hFdTf6GYzEoEfEd4CD-5QqRx0jyBhlVTUQvSDvOs', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='kuodWPn-NMUOuclXdnCA32DdMzj6bFET36-g051oYzs', editable=False, max_length=250),
        ),
    ]
