# Generated by Django 3.1.2 on 2020-10-26 12:44

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201026_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='u6tgkAkmgwilsg0GPQnpxW4VcKePYa_eANX4dHtiE78', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='3mHjHtT0cC5rgTNKVJ4EKzv7rg_OPbKZCa3iNaJTjfg', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
