# Generated by Django 3.1.2 on 2020-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201026_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='ZkBChdRainVidORIX1-sd-kgWgeOOHX1-jSjzHtcTnw', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='wa9Qa2iZRvKmvTmbqJgUp3KjhUhGBZbaGbc2GVBDSB8', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
