# Generated by Django 3.1.2 on 2020-10-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201026_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='f6v7qvZr1PF6nLBOT2y39Iqxlq0NdKzzKV26ztqytSE', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='xvppXp0mIJgWLzB-2RBESC0lKMU6ekkq51QlWjRJfQw', editable=False, max_length=250),
        ),
    ]
