# Generated by Django 3.1.2 on 2020-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201026_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='WS-JWdaSizj1UAhCPsiKPzuiAxiu7aiklrrSIHNENzk', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='tTGaPF6NqZJhEWdzvUepEZjE2W3VBlqnxqgD5MYeZ3Q', editable=False, max_length=250),
        ),
    ]
