# Generated by Django 3.1.2 on 2020-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201026_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='nSInz-uaf7wnuUyg9-_-v4drFm2D6SkunYpvlpYUmbo', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='PQDXqtiGFX714oVSYfv_PivFOaWhk_ogtxDzmCsakDI', editable=False, max_length=250),
        ),
    ]
