# Generated by Django 3.1.2 on 2020-10-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20201026_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='I3HIP53EwyD1STsFwTxr0pAjpP_4Cn_XGVBinIdX9Qc', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='UrTxyE1IDtb_5fFVTCJNx1mkLLDkEyAD4g3TsiUWRnA', editable=False, max_length=250),
        ),
    ]
