# Generated by Django 3.1.2 on 2020-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201026_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='zuyn_Qham60QgtIJWXR_8nnmJ7XuWvTPwPt_m8Ii5vw', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='I-W_ZNQzW3K5EV_7WvSVzJNxeMm0EajabmCNRDW_mMI', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
