# Generated by Django 3.1.2 on 2020-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20201026_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='ncoTPrSHk1uF21EvkT0zn1VdAWqrSxlluL-Z3Igj450', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='T8fSDNq4qA5gNcnsKllj02yy_MY-OCeVKOUbavv6ApQ', editable=False, max_length=250),
        ),
    ]
