# Generated by Django 3.1.2 on 2020-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201026_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='7vFN2bAz8IMVEClWAVs1kN_pbA9qwfNj358mY0cPOYk', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='HY4QCKGoHmwuoa2jXNPU2r9EQkmsBeXFisKdf9zUbjI', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
