# Generated by Django 3.1.2 on 2020-10-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20201027_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='hJSnc_Fpjk3aPPYsn_2VnC4sXLIuOHa0fPAr4CABYAA', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='XoS0wKYKKYp_esYTuzqOlIWy_of2nnFhyTyQBz0FFY0', editable=False, max_length=250),
        ),
    ]
