# Generated by Django 3.1.2 on 2020-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201027_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='5ZxHqYgVtSpPnSYn_EuHGYklHRgCxRKSQ7i9PNG94Ro', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='vGS4X9UfLSMzsd-yTnMT09h9Fvk5dYeg70o5Q_K0sO0', editable=False, max_length=250),
        ),
    ]
