# Generated by Django 3.1.2 on 2020-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20201027_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='sT59-DRriAsLw7iT7jyI1Mech2-AqrYzf4fCbP-dtzE', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='GJdC_ZofdC0oCcWeCkd8s_OlpuFhkKvO4K0E-m1WRGk', editable=False, max_length=250),
        ),
    ]
