# Generated by Django 3.1.2 on 2020-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20201027_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='YEHEvhzJqTOGqp7udhPqU6JpeXGwkh0OAgV-XDkKbt0', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='grmBaw-eyVuGXc88JhyrAM7baAtbuStBDG5ohRPtX1c', editable=False, max_length=250),
        ),
    ]
