# Generated by Django 3.1.2 on 2020-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20201027_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='kN-J9tNKqXkF3V_kqZTTsMhLm0PNYuRKZmfUrevyAwU', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='lITRlb2OfXGrAMtCP-HAiTqev5uHFs2j15pOzvHB3Lo', editable=False, max_length=250),
        ),
    ]
