# Generated by Django 3.1.2 on 2020-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20201028_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='DUsYE_l0zKGePgkMefWUB9iBgxx0xNC5JVGScf9lO2Q', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='x0P8k_m3t8bHku7G6IasUI1dr9T5W5m5NhKuj_gCvdk', editable=False, max_length=250),
        ),
    ]
