# Generated by Django 3.1.2 on 2020-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20201028_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='jq7fu7uu8Kmmh5qSr6WLzRotbBDJHs9dnJOOXT7cOxc', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='mq28fR5Ga6GdEf8Y8M0O4ab0xbmuW_ZXGZkwSCu1nDM', editable=False, max_length=250),
        ),
    ]
