# Generated by Django 3.1.2 on 2020-10-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20201029_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='token',
            field=models.CharField(default='ovjFKS9ZdmLTAZIKzVERaDPIrCq3bqdTwyztE-WG61k', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='url_token',
            field=models.CharField(default='0wNkO7gqCapm3gDJ_8xbcT_Y_-lrRSvYyMvkWijc7AM', editable=False, max_length=250),
        ),
    ]
