# Generated by Django 3.1.2 on 2020-10-24 17:48

import django.contrib.postgres.fields
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brand/image')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ManyToManyField(related_name='brand', related_query_name='brand', to='shopit.Brand')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FilterCategory',
                'verbose_name_plural': 'FilterCategories',
            },
        ),
        migrations.CreateModel(
            name='filterValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MiddlePriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('start_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('start_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('end_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('end_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MiddlePriceRange',
                'verbose_name_plural': 'MiddlePriceRanges',
            },
        ),
        migrations.CreateModel(
            name='PriceFilterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('under_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('under_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('middle_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('middle_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('above_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('INR', 'INR ₹'), ('USD', 'USD $')], default='INR', editable=False, max_length=3)),
                ('above_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='INR', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PriceFilterCategory',
                'verbose_name_plural': 'PriceFilterCategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ManyToManyField(to='shopit.Category')),
                ('filter_category', models.ManyToManyField(to='shopit.FilterCategory')),
                ('price_filter_category', models.ManyToManyField(to='shopit.PriceFilterCategory')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='FilterProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.ManyToManyField(to='shopit.filterValues')),
            ],
        ),
        migrations.AddField(
            model_name='filtercategory',
            name='properties',
            field=models.ManyToManyField(related_name='FilterProperty', related_query_name='FilterProperties', to='shopit.FilterProperties'),
        ),
    ]
