# Generated by Django 3.1.2 on 2020-10-25 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopit', '0002_create_product_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='ProductFAQ',
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='ProductFAQAnswer',
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='properties',
            field=models.ManyToManyField(to='shopit.FilterProperties'),
        ),
        migrations.AlterField(
            model_name='filterproperties',
            name='value',
            field=models.ManyToManyField(to='shopit.FilterValues'),
        ),
    ]
