# Generated by Django 3.1.2 on 2020-10-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0004_auto_20201025_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterproperties',
            name='value',
            field=models.ManyToManyField(to='shopit.FilterValues'),
        ),
    ]
