# Generated by Django 3.1.2 on 2020-10-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0009_auto_20201026_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterproperties',
            name='value',
            field=models.ManyToManyField(to='shopit.FilterValues'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopit.brand'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopit.category'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='faq',
            field=models.ManyToManyField(blank=True, to='shopit.ProductFAQ'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='review',
            field=models.ManyToManyField(blank=True, to='shopit.ProductReview'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='shopit.SubCategory'),
        ),
    ]
