# Generated by Django 3.1.2 on 2020-10-26 14:04

from django.conf import settings
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopit', '0011_auto_20201026_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='filterproperties',
            name='value',
            field=models.ManyToManyField(blank=True, to='shopit.FilterValues'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='filter_category',
            field=models.ManyToManyField(blank=True, to='shopit.FilterCategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='price_filter_category',
            field=models.ManyToManyField(blank=True, to='shopit.PriceFilterCategory'),
        ),
    ]
