# Generated by Django 3.1.2 on 2020-10-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201027_0137'),
        ('shopit', '0016_auto_20201027_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterproperties',
            name='value',
            field=models.ManyToManyField(blank=True, to='shopit.FilterValues'),
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='seller',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.seller'),
        ),
    ]
