# Generated by Django 3.1.2 on 2020-10-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0018_auto_20201027_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('available_options', models.ManyToManyField(blank=True, to='shopit.AvailableOptions')),
            ],
        ),
        migrations.DeleteModel(
            name='MiddlePriceRange',
        ),
        migrations.RenameField(
            model_name='filterproperties',
            old_name='values',
            new_name='filter_values',
        ),
        migrations.RemoveField(
            model_name='filtervalues',
            name='value',
        ),
        migrations.AddField(
            model_name='filtervalues',
            name='max_possible_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='filtervalues',
            name='min_possible_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='filterproperties',
            name='filter_values',
            field=models.ManyToManyField(blank=True, to='shopit.FilterValues'),
        ),
        migrations.AddField(
            model_name='filterproperties',
            name='select_values',
            field=models.ManyToManyField(blank=True, to='shopit.SelectValues'),
        ),
    ]
