# Generated by Django 3.1.2 on 2020-10-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0019_auto_20201027_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableOptions',
            new_name='AvailableFilterSelectOptions',
        ),
        migrations.RenameModel(
            old_name='SelectValues',
            new_name='FilterValuesSelect',
        ),
        migrations.RenameModel(
            old_name='filterValues',
            new_name='FilterValuesText',
        ),
    ]
