# Generated by Django 3.1.2 on 2020-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0021_auto_20201028_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='stoke',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
