# Generated by Django 3.1.2 on 2020-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0023_availablefilterselectoptions_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
