# Generated by Django 3.1.2 on 2020-10-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopit', '0024_auto_20201028_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='filter_details',
            new_name='product_details',
        ),
    ]
