# Generated by Django 3.1.2 on 2020-10-29 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopit', '0026_auto_20201029_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='brand',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='productfaq',
            old_name='answer',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='faq',
            new_name='faqs',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='review',
            new_name='reviews',
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='sub_category',
            new_name='sub_categories',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='report',
            new_name='reports',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
